[project]
name = "openai-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "openai-agents>=0.2.3",
    "python-decouple>=3.8",
    "streamlit>=1.47.0",
]
